<?php
$course = [
    'slug' => 'full-stack-development-course-jaipur',
    'short_name' => 'Full Stack Development',
    'h1' => 'Full Stack Development Course in Jaipur',
    'eyebrow' => 'React + Node.js + APIs + SQL/NoSQL + Deployment',
    'headline' => 'Build, Connect, Debug and Deploy Complete Web Applications',
    'summary' => 'Develop frontend and backend skills in one structured path covering responsive UI, modern JavaScript, React-oriented development, Node.js services, REST APIs, SQL and NoSQL data, Git workflow and deployment. The current Node.js full stack fee structure combines the approved frontend track with Node.js backend training, with SQL and NoSQL concepts included as complementary learning for the track.',
    'image' => 'assests/Mango%20engineers%20images/full-stack-development-course-jaipur-mango-engineers.webp',
    'highlights' => [
        ['Frontend Skills', 'HTML, CSS, responsive design, JavaScript and modern frontend development foundations.'],
        ['Modern JavaScript', 'Progress from core JavaScript into advanced JavaScript concepts and modern application development.'],
        ['Node.js Backend', 'Learn server-side JavaScript, API development and backend application structure.'],
        ['Database Path', 'Work with SQL and NoSQL concepts as part of full stack application development.'],
    ],
    'who_for' => [
        'Beginners who want an end-to-end web development path.',
        'Students and freshers preparing for frontend/full stack roles.',
        'Frontend learners who want to add backend development.',
        'Developers who want a JavaScript-based full stack roadmap.',
    ],
    'outcomes' => [
        'Build responsive web interfaces using HTML, CSS and modern CSS frameworks.',
        'Use JavaScript to build interactive application behaviour.',
        'Understand advanced JavaScript and modern ES concepts.',
        'Build backend services with Node.js.',
        'Create and consume APIs and connect applications to databases.',
        'Combine frontend and backend code into deployable full stack projects.',
    ],
    'syllabus' => [
        ['title' => 'Web & Responsive UI Foundations', 'items' => ['HTML5 semantic structure', 'CSS3', 'Responsive design', 'Flexbox and Grid', 'Bootstrap / Tailwind foundations', 'Browser DevTools']],
        ['title' => 'Modern JavaScript', 'items' => ['JavaScript ES6+', 'Functions, arrays and objects', 'DOM and events', 'Forms and validation', 'Async JavaScript', 'Fetch and JSON']],
        ['title' => 'React-Oriented Frontend Development', 'items' => ['Components and JSX', 'Props and state', 'Hooks', 'Routing', 'Reusable forms', 'API-connected interfaces']],
        ['title' => 'Node.js & Backend Services', 'items' => ['Node.js runtime and modules', 'Express-style routing', 'Middleware', 'REST API design', 'Validation', 'Error handling']],
        ['title' => 'Authentication & Application Security', 'items' => ['Authentication concepts', 'Protected routes', 'Authorization basics', 'Input validation', 'Environment variables', 'Secure configuration habits']],
        ['title' => 'SQL & NoSQL Databases', 'items' => ['Relational data modelling', 'SQL CRUD and joins', 'Transactions basics', 'MongoDB-style documents', 'Indexes', 'Database integration']],
        ['title' => 'Git, Testing & Deployment', 'items' => ['Git and GitHub workflow', 'Branches and documentation', 'API testing', 'Debugging full stack data flow', 'Deployment configuration', 'Production verification']],
        ['title' => 'Portfolio & Interview Preparation', 'items' => ['Project README and architecture notes', 'Live project presentation', 'JavaScript / React review', 'Node.js / API review', 'Database questions', 'Problem-solving practice']],
    ],
    'projects' => ['Responsive multi-page application with validated forms', 'React-oriented API dashboard with loading and error states', 'Authenticated Node.js CRUD/API project with database persistence', 'E-commerce or booking workflow connecting frontend, backend and data', 'Deployed full stack capstone with GitHub documentation'],
    'career_roles' => ['Frontend / React Developer', 'Node.js Backend Developer', 'Junior Full Stack Developer', 'JavaScript Developer', 'Web Application Developer'],
    'fees' => [['Frontend Track', '₹20,000'], ['Node.js Backend', '₹8,500'], ['Complete Node Full Stack', '₹28,500'], ['SQL + NoSQL', 'Complementary in this track']],
    'faq' => [
        ['What is included in the ₹28,500 full stack fee?', 'The currently supplied structure combines the frontend track at ₹20,000 with Node.js backend at ₹8,500. SQL and NoSQL are complementary within this track.'],
        ['Does the frontend track include React?', 'The approved frontend structure includes web design, advanced JavaScript and React-oriented learning. Confirm the current batch sequence and exact React coverage during counselling.'],
        ['Can a beginner join Full Stack Development?', 'Yes, provided the batch starts from frontend and programming foundations. Learners with prior JavaScript knowledge may progress faster.'],
        ['Will I build projects?', 'Yes. The learning path is structured around practical frontend, backend and full stack project work, including API-driven and database-backed applications.'],
        ['Will I learn Git, GitHub and deployment?', 'The learning path includes version-control workflow, project documentation and deployment-oriented practice so learners can package and present working applications.'],
        ['Do I learn both SQL and NoSQL?', 'Yes. The current structure includes SQL and NoSQL concepts as complementary learning within the Node.js full stack track.'],
        ['How should I prepare a portfolio for full stack roles?', 'Use a small set of working projects that show increasing complexity, clear documentation, APIs, database integration and a deployed demonstration where practical.'],
        ['Is placement guaranteed?', 'No. Mango Engineers can support portfolio, interview and placement preparation, but no employment outcome is guaranteed.'],
    ],
    'related' => [['Java Full Stack', 'course-one.html#full-stack'], ['Python Full Stack', 'course-one.html#full-stack'], ['Java Programming', 'java-course-jaipur.html'], ['Python Programming', 'python-course-jaipur.html']],
];
require __DIR__ . '/../includes/course-page.php';
